# @package _group_

defaults:
  - feature: fbank
  - augment: default
  - dataset: voxceleb2
  - criterion: pyannote_aamsoftmax
  - lr_scheduler: warmup_reduce_lr_on_plateau
  - model: clovaai_ecapa
  - trainer: cpu
